### FINAL CONFIG

Pets:
  task: "Pets"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 500
  batch_size: 32

SUN397:
  task: "SUN397"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
#    sgd-0.0001:
#      optimizer: "sgd"
#      lr: 0.0001
  num_epochs: 250
  batch_size: 32

CIFAR-100:
  task: "CIFAR-100"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 100
  batch_size: 32

CalTech-101:
  task: "CalTech-101"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 500
  batch_size: 32

Eurosat:
  task: "Eurosat"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 200
  batch_size: 32

dtd:
  task: "dtd"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 100
  batch_size: 32

CLEVERNumObjects:
  task: "CLEVERNumObjects"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 100
  batch_size: 32

THORNumSteps:
  task: "THORNumSteps"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 100
  batch_size: 32

Imagenet:
  task: "Imagenet"
  training_configs:
    adam-1:
      optimizer: "adam"
      lr: 1
    adam-0.1:
      optimizer: "adam"
      lr: 0.1
    adam-0.01:
      optimizer: "adam"
      lr: 0.01
    adam-0.001:
      optimizer: "adam"
      lr: 0.001
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#      scheduler:
#        type: "StepLR"
#        step_size: 50
#        gamma: 0.1
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
#      scheduler:
#        type: "StepLR"
#        step_size: 50
#        gamma: 0.1
  num_epochs: 100
  batch_size: 32

THORActionPrediction:
  task: "THORActionPrediction"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 100
  batch_size: 32

THORDepth:
  task: "THORDepth"
  pre_encode: false
  training_configs:
    adam-0.0001-l1:
      optimizer: "adam"
      lr: 0.0003
#    sgd-0.01-l1:
#      optimizer: "sgd"
#      lr: 0.01
  num_epochs: 50
  batch_size: 16

NYUDepth:
  task: "NYUDepth"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    sgd-0.001-no-step-l1:
#      optimizer: "sgd"
#      lr: 0.001
#      scheduler:
#        type: "StepLR"
#        step_size: 500
#        gamma: 0.1
  num_epochs: 250
  batch_size: 16

TaskonomyInpainting:
  task: "TaskonomyInpainting"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    sgd-0.01-l1:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 25

TaskonomyEdges:
  task: "TaskonomyEdges"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    sgd-0.01-l1:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 10

COCODetection:
  task: "COCODetection"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    sgd-0.01-l1:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 25

#Imagenetv2:
#  task: "Imagenetv2"
#  task_head_weights_path: "out/%s/Imagenet*/model_head.pt"
#  training_configs:
#    adam-0.0003:
#      optimizer: "adam"
#      lr: 0.0003
#  batch_size: 32

KineticsActionPrediction:
  task: "KineticsActionPrediction"
  pre_encode: true
  training_configs:
#    adam-0.0003:
#      optimizer: "adam"
#      lr: 0.0003
    adam-0.01:
      optimizer: "adam"
      lr: 0.0003
      scheduler:
        type: "Linear"
  num_epochs: 100
  batch_size: 32

EgoHands:
  task: "EgoHands"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    adam-0.01:
#      optimizer: "adam"
#      lr: 0.0003
#      scheduler:
#        type: "Linear"
  num_epochs: 25
  batch_size: 16

KITTI:
  task: "KITTI"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    adam-0.01:
#      optimizer: "adam"
#      lr: 0.0003
#      scheduler:
#        type: "Linear"
  num_epochs: 250
  batch_size: 16

nuScenesActionPrediction:
  task: "nuScenesActionPrediction"
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 100
  batch_size: 32

#### FIX THESE
#
TaskonomyDepth:
  task: "TaskonomyDepth"
  pre_encode: false
  training_configs:
    adam-0.0001:
      optimizer: "adam"
      lr: 0.0003
#    sgd-0.01-l1:
#      optimizer: "sgd"
#      lr: 0.01
  num_epochs: 50
  batch_size: 16

CityscapesSemanticSegmentation:
  task: "CityscapesSemanticSegmentation"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
      scheduler:
        type: "Poly"
        exponent: 0.9
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.001
#      scheduler:
#        type: "StepLR"
#        step_size: 25
#        gamma: 0.3
  num_epochs: 100
  batch_size: 16

NYUWalkable:
  task: "NYUWalkable"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    sgd-0.001-no-step-l1:
#      optimizer: "sgd"
#      lr: 0.001
#      scheduler:
#        type: "StepLR"
#        step_size: 40
#        gamma: 0.1
  num_epochs: 250
  batch_size: 16

Pets-Detection:
  task: "Pets-Detection"
  pre_encode: false
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 100
  batch_size: 16
