### FINAL CONFIG
#
Pets-Detection:
  task: "Pets-Detection"
  training_configs:
    adam-0.0003:
      optimizer: "adam"
      lr: 0.0003
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
  num_epochs: 100
#
#THORDepth:
#  task: "THORDepth"
#  training_configs:
#    adam-0.0001-l1:
#      optimizer: "adam"
#      lr: 0.0003
##    sgd-0.01-l1:
##      optimizer: "sgd"
##      lr: 0.01
#  num_epochs: 50
#
#NYUDepth:
#  task: "NYUDepth"
#  training_configs:
#    adam-0.0003-l1:
#      optimizer: "adam"
#      lr: 0.0003
##    sgd-0.001-no-step-l1:
##      optimizer: "sgd"
##      lr: 0.001
##      scheduler:
##        type: "StepLR"
##        step_size: 40
##        gamma: 0.1
#  num_epochs: 40
#  num_dataset_repeats: 25
#
#NYUWalkable:
#  task: "NYUWalkable"
#  training_configs:
#    adam-0.0003-l1:
#      optimizer: "adam"
#      lr: 0.0003
##    sgd-0.001-no-step-l1:
##      optimizer: "sgd"
##      lr: 0.001
##      scheduler:
##        type: "StepLR"
##        step_size: 40
##        gamma: 0.1
#  num_epochs: 40
#  num_dataset_repeats: 25
#
#

#Imagenet:
#  task: "Imagenet"
#  training_configs:
#    adam-0.0001:
#      optimizer: "adam"
#      lr: 0.0001
#    adam-0.001:
#      optimizer: "adam"
#      lr: 0.001
#    sgd-0.01:
#      optimizer: "sgd"
#      lr: 0.01
#      scheduler:
#        type: "StepLR"
#        step_size: 50
#        gamma: 0.1
#    sgd-0.001:
#      optimizer: "sgd"
#      lr: 0.001
#      scheduler:
#        type: "StepLR"
#        step_size: 50
#        gamma: 0.1
#  num_epochs: 100

#TaskonomyInpainting:
#  task: "TaskonomyInpainting"
#  pre_encode: true
#  training_configs:
#    adam-0.0001-l1:
#      optimizer: "adam"
#      lr: 0.0003
##    sgd-0.01-l1:
##      optimizer: "sgd"
##      lr: 0.01
#  num_epochs: 25
