## Baselines
Random: 'pretrained_weights/Random.pt'
Supervised: 'pretrained_weights/Supervised.pt'
## Pre Trained
SWAV_800: 'pretrained_weights/SWAV_800.pt'
MoCov2_800: 'pretrained_weights/MoCov2_800.pt'
MoCov1_200: 'pretrained_weights/MoCov1_200.pt'
PIRL: 'pretrained_weights/PIRL_800.pt'
SimCLR_1000: 'pretrained_weights/SimCLR_1000.pt'
## MoCo
MoCov2_200: 'pretrained_weights/MoCov2_800.pt'
MoCov2Combination: 'pretrained_weights/MoCov2Combination.pt'
MoCov2Taskonomy: 'pretrained_weights/MoCov2Taskonomy.pt'
MoCov2Kinetics: 'pretrained_weights/MoCov2Kinetics.pt'
MoCov2Places: 'pretrained_weights/MoCov2Places.pt'
MoCov2HalfImagenet: 'pretrained_weights/MoCov2HalfImagenet_200.pt'
MoCov2LogImagenet: 'pretrained_weights/MoCov2LogImagenet.pt'
## SWAV
SWAV_200: 'pretrained_weights/SWAV_200.pt'
SWAVCombination: 'pretrained_weights/SWAVCombination.pt'
SWAVTaskonomy: 'pretrained_weights/SWAVTaskonomy.pt'
SWAVKinetics: 'pretrained_weights/SWAVKinetics.pt'
SWAVPlaces: 'pretrained_weights/SWAVPlaces.pt'
SWAVHalfImagenet: 'pretrained_weights/SWAVHalfImagenet.pt'
SWAVLogImagenet: 'pretrained_weights/SWAVLogImagenet.pt'
