SWAV_800: 'pretrained_weights/SWAV_800.pt'
MoCov2_800: 'pretrained_weights/MoCov2_800.pt'
#SWAV_200: 'pretrained_weights/SWAV_200.pt'
#SWAVCombination: 'pretrained_weights/SWAVCombination.pt'
#SWAVTaskonomy: 'pretrained_weights/SWAVTaskonomy.pt'
#SWAVKinetics: 'pretrained_weights/SWAVKinetics.pt'
#SWAVPlaces: 'pretrained_weights/SWAVPlaces.pt'
#SWAVHalfImagenet: 'pretrained_weights/SWAVHalfImagenet.pt'
#SWAVLogImagenet: 'pretrained_weights/SWAVLogImagenet.pt'
