#### FINAL CONFIG
#SUN397:
#  task: "SUN397"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500

#CIFAR-100:
#  task: "CIFAR-100"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#Caltech101:
#  task: "CalTech-101"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#CLEVERNumObjects:
#  task: "CLEVERNumObjects"
#  optimizer: "adam"
#  lr: 0.001
#  num_epochs: 500
#Pets:
#  task: "Pets"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#dtd:
#  task: "dtd"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#Eurosat:
#  task: "Eurosat"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500

#PetsDetection-sgd-0.01-full-sized-output:
#  task: "Pets-Detection"
#  optimizer: "sgd"
#  lr: 0.01
#  num_epochs: 500
#  scheduler:
#    step_size: 100
#    gamma: 0.5

PetsDetectio-sgd-0.001-full-sized-output-saving:
  task: "Pets-Detection"
  optimizer: "sgd"
  lr: 0.001
  num_epochs: 500
  scheduler:
    step_size: 100
    gamma: 0.5

#dtd-adam-0.0001:
#  task: "dtd"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#dtd-adam-0.001:
#  task: "dtd"
#  optimizer: "adam"
#  lr: 0.001
#  num_epochs: 500
#dtd-sgd-0.001:
#  task: "dtd"
#  optimizer: "sgd"
#  lr: 0.001
#  num_epochs: 500
#dtd-sgd-0.01:
#  task: "dtd"
#  optimizer: "sgd"
#  lr: 0.01
#  num_epochs: 500

#CLEVERDist-adam-0.0001:
#  task: "CLEVERDist"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#CLEVERDist-adam-0.001:
#  task: "CLEVERDist"
#  optimizer: "adam"
#  lr: 0.001
#  num_epochs: 500
#CLEVERDist-sgd-0.001:
#  task: "CLEVERDist"
#  optimizer: "sgd"
#  lr: 0.001
#  num_epochs: 500
#CLEVERDist-sgd-0.01:
#  task: "CLEVERDist"
#  optimizer: "sgd"
#  lr: 0.01
#  num_epochs: 500
#
