Caltech101-10-1:
  task: "CalTech-101"
  optimizer: "sgd"
  lr: 10
  num_epochs: 100
Caltech101-10-2:
  task: "CalTech-101"
  optimizer: "sgd"
  lr: 10
  num_epochs: 100
Caltech101-1-1:
  task: "CalTech-101"
  optimizer: "sgd"
  lr: 1
  num_epochs: 100
Caltech101-1-2:
  task: "CalTech-101"
  optimizer: "sgd"
  lr: 1
  num_epochs: 100
Caltech101-0.1-1:
  task: "CalTech-101"
  optimizer: "sgd"
  lr: 0.1
  num_epochs: 100
Caltech101-0.1-2:
  task: "CalTech-101"
  optimizer: "sgd"
  lr: 0.1
  num_epochs: 100

