#### FINAL CONFIG
#SUN397:
#  task: "SUN397"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#Caltech101:
#  task: "CalTech-101"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#CLEVERNumObjects:
#  task: "CLEVERNumObjects"
#  optimizer: "adam"
#  lr: 0.001
#  num_epochs: 500

PetsDetection-train-encoder:
  task: "Pets-Detection"
  optimizer: "adam"
  lr: 0.0001
  num_epochs: 100
  pre_encode: True

#CLEVERDist-adam-0.0001:
#  task: "CLEVERDist"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#CLEVERDist-adam-0.001:
#  task: "CLEVERDist"
#  optimizer: "adam"
#  lr: 0.001
#  num_epochs: 500
#CLEVERDist-sgd-0.001:
#  task: "CLEVERDist"
#  optimizer: "sgd"
#  lr: 0.001
#  num_epochs: 500
#CLEVERDist-sgd-0.01:
#  task: "CLEVERDist"
#  optimizer: "sgd"
#  lr: 0.01
#  num_epochs: 500
#
