#### FINAL CONFIG
#SUN397:
#  task: "SUN397"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500
#Caltech101:
#  task: "CalTech-101"
#  optimizer: "adam"
#  lr: 0.0001
#  num_epochs: 500

CLEVERNumObjects-adam-0.0001:
  task: "CLEVERNumObjects"
  optimizer: "adam"
  lr: 0.0001
  num_epochs: 500
CLEVERNumObjects-adam-0.001:
  task: "CLEVERNumObjects"
  optimizer: "adam"
  lr: 0.001
  num_epochs: 500
CLEVERNumObjects-sgd-0.001:
  task: "CLEVERNumObjects"
  optimizer: "sgd"
  lr: 0.001
  num_epochs: 500
CLEVERNumObjects-sgd-0.01:
  task: "CLEVERNumObjects"
  optimizer: "sgd"
  lr: 0.01
  num_epochs: 500

